nome = str(input("Digite seu nome: "))
print("Olá {}, tudo bem?".format(nome))
print("Espero que sim!... \nMeu nome e VanTec-9000, e hoje eu vou te ajudar com uma soma!")
print("Por favor siga os passos que eu vou te pedir, é bem fácil!")
n1 = int(input("Digite um número: "))
print("Muito Bem! \nAgora vamos mais uma vez!")
n2 = int(input("Digite outro número: "))
print("Isso aí, não foi tão difícil né?")
print("Agora estou vendo quais números você escolheu...")
print("Hum... só mais um minutinho...")
print("Estou vendo que você escolheu o número {} é o número {}.".format(n1,n2))
print("Vamos lá {}, agora é só somarmos os dois números que você escolheu.".format(nome))
print("Somando os números...")
print("só mais um pouquinho...")
print("Prontinho")
print("A soma de {} + {} é igual á {}.".format(n1,n2,n1+n2))
print("Concluímos nossa missão! \nAté a proxima {}".format(nome))