n1 = int(input("Digite um número: "))
n2 = int(input("Digite outro número: "))

print("-="*20)
print("**ADIÇÃO**")
print("A soma de {} + {} é igual á {}".format(n1,n2,n1+n2))
print("-="*20)
print("**SUBTRAÇÃO**")
print("A subtração de {} - {} é igual á {}".format(n1,n2,n1-n2))
print("-="*20)
print("**MULTIPLICAÇÃO**")
print("A multiplicação de {} * {} é igual á {}".format(n1,n2,n1*n2))
print("-="*20)
print("**DIVISÃO**")
print("A divisão de {} / {} é igual á {}".format(n1,n2,n1/n2))
print("-="*20)
print("**POTENCIA**")
print("A potenciação de {} ** {} é igual á {}".format(n1,n2,n1**n2))
print("-="*20)
print("**RESTO**")
print("O resto de {} % {} é igual á {}".format(n1,n2,n1%n2))
print("-="*20)

